language: node_js
node_js:
  - "6"
script:
  - npm run test-client
  - npm run test-server
  - npm run build-client

install:
  - npm run install-deps

notifications:
  email: false

branches:
  only:
    - next
